### ISSUE TITLE
are there any way ffi for python?

### ISSUE THREAD

**Issue by future-guard** [Zondax/filecoin-signing-tools#341]
OS : macos
any way to ffi for python 3.7?

i just import `libfilecoin_signer_ffi.dylib` on python  by cdll 
and call some methods on dylib but it occur something segfault. 

:link: [zboto Link](https://app.clickup.com/t/2r5b6e9)

**Comment by becominginsane** [comment]
I investigated a bit, and perhaps your issue has been fixed in the 2 years it's been open, but I was able to use the library from Lisp without segfault.
It depends on how you used the library, but perhaps you provided a non-zero terminated string? Currently we are using `ffi_support::FfiStr` which wants a 0-terminated string like C's.
Not sure what's python's behavior about passing strings via FFI.

If it's still a problem please reopen with more detailed error reproduction steps, thanks!
