### ISSUE TITLE
Provide multisig examples for serializing / deserializing multisig messages

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#353]
As discussed in Slack, it would be great to have support for all the multisig methods [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_actor.go#L52-L64). This does not include proposing arbitrary contract calls, only known contract calls. 

And according to @jleni - in order to provide examples, we need to fix all the missing pieces!

**Comment by Schwartz10** [comment]
(this should include deserializing constructor params too, from the msig initialization). For example:

https://filfox.info/en/message/bafy2bzaceacyyowgzjc3q3ylrd7zl7wlmhlywt7sjesqfx737vapxcbbdmfhm

(we had this working a few months ago, but it seems to have broken for some reason!)

**Comment by rllola** [comment]
Hi @Schwartz10 

It has been a while. Could you update me on this? 

We have a way to deserialize all the parameters for all the multisig methods (see https://github.com/Zondax/filecoin-signing-tools/blob/master/signer/src/lib.rs#L1091-L1135). Let me know if I missed one.

Regarding the constructor, you might need to call `deserializeConstructorParams` after calling `deserializeParams`. It should be possible to give directly the deserialized paremeters used when initiating the multisig contract tho.

**Comment by Schwartz10** [comment]
@rllola I'll close this for now, going to revisit in September to build support for all multisig methods into the Glif Wallet and will let you know if there are any questions

**Comment by herryho** [comment]
Hi @rllola 
I'm trying the examples for deserializeParams funtion, but it didn't work. I got an error saying "Error: `Actor type not supported". It seems any Actor type such as "multisig", "paymentchannel" etc. won't work. Do you have any idea what the problem is?

example link:
https://github.com/Zondax/filecoin-signing-tools/blob/945ed77a36ca1f45f075b0e15b1e3c1ae97b5af8/docs/wasm_api.md#L441

My code:
`
const filecoin_signer = require('@zondax/filecoin-signing-tools');

function main() {
  let base64_params =
    'glUB/R0PTfzX6Zr8uZqDJrfcRZ0yxihVAR6vHIpLv+6whwsXRbH1dQNHC3EW';

  let result = filecoin_signer.deserializeParams(base64_params, 'multisig', 7);

  console.log(`result: ${JSON.stringify(result)}`);
}
main();
`

Error screenshot:
![image](https://user-images.githubusercontent.com/45537372/214862768-ddc90a7d-f922-4984-92eb-1ebed71f7f6d.png)

**Comment by rllola** [comment]
@herryho That's weird it is definitely a supported actor. Could you tell me which version you are using ?

**Comment by herryho** [comment]
@rllola The version of @zondax/filecoin-signing-tools is 1.1.2.

**Comment by rllola** [comment]
@herryho Try to update and use the latest one https://github.com/Zondax/filecoin-signing-tools/releases/tag/v2.3.0

It is 2.3.0
